spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/crawler
    username: crawler_user
    password: crawler_pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    com.avdemchenko.webcrawler: debug
